# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8c607c97232d63a952743985dd1908679c3ef6119edb63d647b4d6f55858d7a54974701b1611fe7495d5ab3e0a6378ffb3a37c1c939e186e359f696d787dc1b

test:
  secret_key_base: cffb0d3ab0d29ecb77e9c0feac539a5c8a3dab11ad7ba89c67a11dd68581b76508f3a7a4d94b423c9879ca824f06ea6e01dc469770c10dc0364f40607c8a9eec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
